### ISSUE TITLE
Bug: Repository Key untrusted. - apt-key deprecated

### ISSUE THREAD

**Issue by TBuban** [Cyclenerd/scp-tools-gitlab#14]
Hi Nils,

first of all, I have to say how great your work is, thank you for this. :) 

But unfortunately, I mustreport a bug. During our pipeline run we install some additional software. This step fails, because some gpg signatures are invalid. 

W: [http://dist.sapmachine.io/debian/amd64/./InRelease](http://dist.sapmachine.io/debian/amd64/InRelease): Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packages.cloudfoundry.org/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://cf-cli-debian-repo.s3.amazonaws.com/ stable InRelease: The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
E: The repository 'https://packages.cloudfoundry.org/debian stable InRelease' is not signed.
 
I’m not sure if this belongs to the problem hat apt-key is deprecated. But probably you could change this as well with the new release of the image. 😊

Many Thanks and best regards, 

Thomas

**Comment by theCalcaholic** [comment]
Unfortunately, that's an [upstream issue](https://github.com/cloudfoundry/cli/issues/2571). 
Also compare https://github.com/Cyclenerd/scp-tools-gitlab/pull/15

**Comment by Cyclenerd** [comment]
Fixed with latest run: https://github.com/Cyclenerd/scp-tools-gitlab/actions/runs/6158053024
